---
title: "testing"
author: "E Robesyn"
date: "27 December 2015"
output: html_document
---


```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(caret)
```

```{r}
setwd("C:/Users/Robesyn/Documents/5 DATA PROJECTS/CourseraMachineLearningProject")
training<-read.csv("./data/pml-training.csv", na.strings  = c("#DIV/0!","","NA"), stringsAsFactors = F) 
training<-tbl_df(training)

dim(training)
glimpse(training)  # last var "classe" is outcome to predict
#View(training)
```

```{r}
testing<-read.csv("./data/pml-testing.csv", na.strings  = c("#DIV/0!","","NA"), stringsAsFactors = F) 
testing<-tbl_df(testing)

dim(testing)  # only check dim but no further inspection of content! (to avoid overfitting by learning from testing dataset)
```


```{r}
names(testing)[1:8]  # to be sure test set has same order of first 7 variables (because I delete them in next step)
testing<-select(testing, -c(1:7)) 
dim(testing)
```

Select var out with many na
```{r}
testing <- testing[, colMeans(is.na(testing)) <= .15]
dim(testing)
```

# preprocessing on training data and apply this preObj (parameters built from training) to the testing!
```{r}
preObj<-preProcess(trainingtrain[,-53], method=c("center","scale", "knnImpute"))
class(preObj)
preObj   # where do the 5 knn imputations come from if there were no NA anymore?
```

From the below results of the random forest algorithm, which includes a cross validation through bootstrapping with 25 repeats, I estimate a 98% out-of-sample accuracy for this classification excercise.  

```{r random forests, cache=TRUE}
# predicting new values based on testing dataset:
pred<-predict(modelFit, testing)
pred
```

```{r}
answers<-pred
answers
answers<-as.character(pred)
answers
class(answers)
```

```{r create answer files}
answers

pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}

# then create a folder where you want the files to be written. Set that to be your working directory and run:
setwd("C:/Users/Robesyn/Documents/5 DATA PROJECTS/CourseraMachineLearningProject/testingpredictions")
pml_write_files(answers)
```

